# Site settings
baseurl: "/micro-acquisition"
url: "https://canada-ca.github.io/micro-acquisition/"

wet_cdts_hosturl: "https://www.canada.ca/etc/designs/canada/cdts/gcweb"
wet_cdts_version: "v4_0_39"

# Build settings
markdown: kramdown
include: ["_pages"]
exclude: ["_posts/en/template*.md", "_posts/fr/gabarit*.md"]
timezone: America/Vancouver
